services:
  backend:
    build: ./backend
    ports:
      - "4001:4001"
    networks:
      - app-network

  frontend:
    build: ./
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
